In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_freed_index=pd.read_csv("fear_greed_index.csv")
df_freed_index.head()

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [5]:
df_historical_data=pd.read_csv("historical_data.csv")
df_historical_data.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [7]:
df_freed_index["date"]=pd.to_datetime(df_freed_index["date"])
df_freed_index.head()

    timestamp  value classification       date
0  1517463000     30           Fear 2018-02-01
1  1517549400     15   Extreme Fear 2018-02-02
2  1517635800     40           Fear 2018-02-03
3  1517722200     24   Extreme Fear 2018-02-04
4  1517808600     11   Extreme Fear 2018-02-05

In [9]:
df_historical_data["date"]=pd.to_datetime(df_freed_index["date"])
df_historical_data.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,date
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2018-02-01
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12,2018-02-02
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12,2018-02-03
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12,2018-02-04
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12,2018-02-05

In [11]:
df_freed_index["date"]=df_freed_index["date"].dt.date
df_historical_data["date"]=df_historical_data["date"].dt.date

In [13]:
df=pd.merge(df_freed_index,df_historical_data,on="date",how="inner")
df.head()

,timestamp,value,classification,date,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,1517463000,30,Fear,2018-02-01,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,1517549400,15,Extreme Fear,2018-02-02,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,1517635800,40,Fear,2018-02-03,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,1517722200,24,Extreme Fear,2018-02-04,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,1517808600,11,Extreme Fear,2018-02-05,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [15]:
df.to_csv("merge_data.csv")

In [17]:
data=pd.read_csv("merge_data.csv")
data.head()

,Unnamed: 0,timestamp,value,classification,date,Account,Coin,Execution Price,Size Tokens,Size USD,...,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0,1517463000,30,Fear,2018-02-01,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,...,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,1,1517549400,15,Extreme Fear,2018-02-02,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,...,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,2,1517635800,40,Fear,2018-02-03,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,...,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,3,1517722200,24,Extreme Fear,2018-02-04,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,...,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,4,1517808600,11,Extreme Fear,2018-02-05,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,...,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [19]:
sample_data = data.sample(500) 
profit = sample_data.groupby('classification')['Closed PnL'].mean()
print(profit)

classification
Extreme Fear     385.796610
Extreme Greed    138.241066
Fear             194.085226
Greed            334.600806
Neutral          -49.074026
Name: Closed PnL, dtype: float64

In [21]:
sample_data = data.sample(500) 
total_profit = sample_data.groupby('classification')['Closed PnL'].sum()
print(total_profit)

classification
Extreme Fear     23676.009625
Extreme Greed    18361.519309
Fear             39379.756283
Greed            42889.364170
Neutral           5128.601535
Name: Closed PnL, dtype: float64

In [23]:
sample_data = data.sample(500) 
risk = sample_data.groupby('classification')['Size Tokens'].mean()
print(risk)

classification
Extreme Fear     3329.362299
Extreme Greed    1854.389831
Fear             1575.193698
Greed            1083.713000
Neutral           852.571458
Name: Size Tokens, dtype: float64

In [25]:
sample_data = data.sample(500) 
total_risk = sample_data.groupby('classification')['Size Tokens'].sum()
print(total_risk)

classification
Extreme Fear     440322.7388
Extreme Greed    157688.3400
Fear             210802.7500
Greed            358056.4153
Neutral           59069.6253
Name: Size Tokens, dtype: float64

In [27]:
sample_data = data.sample(500) 
risk_usd = sample_data.groupby('classification')['Size USD'].mean()
print(risk)

classification
Extreme Fear     3329.362299
Extreme Greed    1854.389831
Fear             1575.193698
Greed            1083.713000
Neutral           852.571458
Name: Size Tokens, dtype: float64

In [29]:
sample_data = data.sample(500) 
total_risk_usd = sample_data.groupby('classification')['Size USD'].sum()
print(total_risk_usd)

classification
Extreme Fear     268365.05
Extreme Greed    197243.66
Fear             346774.07
Greed            303042.74
Neutral          129318.25
Name: Size USD, dtype: float64

In [74]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Crossed']=le.fit_transform(data['Crossed'])
data.head()

,Unnamed: 0,timestamp,value,classification,date,Account,Coin,Execution Price,Size Tokens,Size USD,...,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0,1517463000,30,Fear,2018-02-01,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,...,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,1,0.345404,8.950000e+14,1.730000e+12
1,1,1517549400,15,Extreme Fear,2018-02-02,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,...,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,1,0.005600,4.430000e+14,1.730000e+12
2,2,1517635800,40,Fear,2018-02-03,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,...,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,1,0.050431,6.600000e+14,1.730000e+12
3,3,1517722200,24,Extreme Fear,2018-02-04,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,...,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,1,0.050043,1.080000e+15,1.730000e+12
4,4,1517808600,11,Extreme Fear,2018-02-05,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,...,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,1,0.003055,1.050000e+15,1.730000e+12

In [120]:
X = data.drop([
    'Closed PnL',
    'timestamp',
    'Timestamp IST',
    'date',
    'Account',
    'Coin',
    'value',
    'Size Tokens',
    'Start Position',
    'Direction',
    'Transaction Hash',
    'Order ID',
    'Crossed',
    'Fee',
    'Trade ID'
], axis=1)
Y = (df['Closed PnL'] > 0).astype(int)

In [122]:
X=pd.get_dummies(X,columns=['classification','Side'],drop_first=True,dtype=int)

In [138]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [140]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [142]:
model=LogisticRegression()
model.fit(X_train_scaled,Y_train)

LogisticRegression()

In [144]:
y_pred=model.predict(X_test_scaled)
print("accuracy score",accuracy_score(Y_test,y_pred)*100,"%")
print("confusion matrix",confusion_matrix(Y_test,y_pred))

accuracy score 75.23629489603024 %
confusion matrix [[253  69]
 [ 62 145]]